# Numpy

This notebook focuses on the numpy library, which is used to perform multi-dimensional matrix operations efficiently. It is an underpinning to a lot of higher level libraries (tensor flow, scikit learn, pandas). It can be useful to understand the basics, so that when one of these higher level libraries doesn't do exactly what you want, you can tweak the underlying numpy array instead.

In [105]:
%matplotlib ipympl
import numpy as np
from IPython.display import Audio
from matplotlib import pyplot as plt


To whet your appetite, take a look at the following example which combines numpy with the Audio rich content display. The first cell demonstrates the creation of beats from interference. The second cell shows how intermittent noise can effect the audio quality.

**EXERCISE:** Adjust the frequencies, sampling rate, duration, and volume until you're satisfied.

In [106]:
from IPython.display import Audio

f1 = 220.0
f2 = 222.0
sampling_rate = 8000
duration = 3

times = np.linspace(0, duration, duration*sampling_rate)
tone = lambda f : np.sin(2 * np.pi * f * times)
signal = tone(f1) + tone(f2)

Audio(data=signal, rate=sampling_rate)

In [107]:
volume = 0.1

mask = np.random.choice([True, False], size=len(times))
noise = np.random.rand(sum(mask)) * volume
signal = tone(f1)
signal[mask] += noise

Audio(data=signal, rate=sampling_rate)

Let's focus on three features of numpy that these examples partially illustrate. 
There are many other features of numpy, but these three form the core utilities.
1. Creating arrays
2. Indexing, Slicing, and Filtering
3. Vectorized Operations

## Creating arrays

There are three primary ways to create numpy arrays: literals, built in functions, and reading files.

In [108]:
literal_example_1d = np.array([1,9,-1,4])
literal_example_2d = np.array([[1,0], [0,-1]])
print(literal_example_1d.shape, " Example: \n", literal_example_1d)
print(literal_example_2d.shape, " Example: \n", literal_example_2d)

(4,)  Example: 
 [ 1  9 -1  4]
(2, 2)  Example: 
 [[ 1  0]
 [ 0 -1]]


In [109]:
print(np.arange(-1, 1, 0.1))
print(np.logspace(0, 9, 10, base=2))
x, y = np.mgrid[0:5, 0:5]
print(x, "\n", y)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]] 
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [110]:
data = np.genfromtxt('../data/beats.csv', delimiter = ",")
x = data[:,0]
y = data[:,1]
plt.figure()
plt.plot(x, y, 'r-', linewidth=2)

FigureCanvasNbAgg()

**EXERCISE:** Can you spot the three built in numpy functions that were used to construct the arrays in the audio examples at the beginning of this notebook?

## Indexing, Slicing, and Masks

Once an array is created, one of the next most common steps is selecting or updating elements of the array. This can be done simply with the usual syntax for indexing and slicing lists in python. But there's also several forms of fancier slicing.

In [111]:
playground = np.random.randn(3,3,3)
print(playground)

[[[-0.6975474   0.92657741  1.79658813]
  [ 1.08995999  1.51150973 -0.86803732]
  [ 1.08325062  1.55856875  0.63868376]]

 [[ 2.03402635 -0.23454181 -0.41406365]
  [-1.02611769 -1.54659488 -0.4379892 ]
  [-1.00906236 -0.23092698 -0.34501647]]

 [[ 0.50766144  0.44270487 -0.06082705]
  [ 0.11358057  2.49056535  1.99775887]
  [-0.50056065 -1.40142151  0.17732117]]]


In [112]:
print(playground[0,1,-1], "\n")
print(playground[:,:,-1], "\n")
print(playground[::-1,1,2], "\n")
print(playground[[0,-1]], "\n")

-0.868037323140287 

[[ 1.79658813 -0.86803732  0.63868376]
 [-0.41406365 -0.4379892  -0.34501647]
 [-0.06082705  1.99775887  0.17732117]] 

[ 1.99775887 -0.4379892  -0.86803732] 

[[[-0.6975474   0.92657741  1.79658813]
  [ 1.08995999  1.51150973 -0.86803732]
  [ 1.08325062  1.55856875  0.63868376]]

 [[ 0.50766144  0.44270487 -0.06082705]
  [ 0.11358057  2.49056535  1.99775887]
  [-0.50056065 -1.40142151  0.17732117]]] 



Aside from indexing and slicing (including fancy slicing), masks are a very useful way to select elements based on one or more conditions.

In [113]:
positive_sigma_mask = (playground > 0) * (playground < 1)
print(positive_sigma_mask, "\n")
print(playground, "\n")
print(playground[positive_sigma_mask], "\n")

[[[False  True False]
  [False False False]
  [False False  True]]

 [[False False False]
  [False False False]
  [False False False]]

 [[ True  True False]
  [ True False False]
  [False False  True]]] 

[[[-0.6975474   0.92657741  1.79658813]
  [ 1.08995999  1.51150973 -0.86803732]
  [ 1.08325062  1.55856875  0.63868376]]

 [[ 2.03402635 -0.23454181 -0.41406365]
  [-1.02611769 -1.54659488 -0.4379892 ]
  [-1.00906236 -0.23092698 -0.34501647]]

 [[ 0.50766144  0.44270487 -0.06082705]
  [ 0.11358057  2.49056535  1.99775887]
  [-0.50056065 -1.40142151  0.17732117]]] 

[0.92657741 0.63868376 0.50766144 0.44270487 0.11358057 0.17732117] 



Masks also also useful for updating select elements, while leaving others alone.

In [114]:
playground[positive_sigma_mask] = 0
print(playground)

[[[-0.6975474   0.          1.79658813]
  [ 1.08995999  1.51150973 -0.86803732]
  [ 1.08325062  1.55856875  0.        ]]

 [[ 2.03402635 -0.23454181 -0.41406365]
  [-1.02611769 -1.54659488 -0.4379892 ]
  [-1.00906236 -0.23092698 -0.34501647]]

 [[ 0.          0.         -0.06082705]
  [ 0.          2.49056535  1.99775887]
  [-0.50056065 -1.40142151  0.        ]]]


**EXERCISES:** 
1. Can you grab the first matrix, all of the first rows, and all of the first columns as three separate slicing operations on playground? 
2. What is the effect of the mask used in the noisy audio signal example?

## Vector Operations

One of the major performance advantages of numpy over standard lists is that most operations are vectorized over the elements of the list. For example, elementwise multiplication can be sped up several orders of magnitude for a large array.  

In [115]:
x_np = np.random.randn(1000)
x_list = [x for x in x_np]
%timeit [x*x for x in x_list]
%timeit x_np * x_np

86.3 µs ± 16.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
1.18 µs ± 191 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


This kind of speedup is essential for working with big data or complex algorithms where basic operations may be performed trillions of times in one run of the program. However, it can come with a significant learning curve for those unaccustomed to thinking in a vectorized fashion. Will start with the basic operations.

In [116]:
x = np.array([0, 1, 2])
A = np.array([[1,-1, 0], 
              [2, 0, 1]])
c = 5

print(x + c)
print(A - c)
print(A + x)

[5 6 7]
[[-4 -6 -5]
 [-3 -5 -4]]
[[1 0 2]
 [2 1 3]]


In [117]:
print(x * c)
print(x * x)
print(x / x)
print(A * x)

[ 0  5 10]
[0 1 4]
[nan  1.  1.]
[[ 0 -1  0]
 [ 0  0  2]]


c:\users\njb1225\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


Notice that, by default, all of the arithmetic operations are applied elementwise (with broadcasting). What if you want to apply matrix operations? There's a couple options:

In [118]:
print(A.dot(x))
print(A @ x)
print(np.matrix(A) * np.matrix(x).T)

[-1  2]
[-1  2]
[[-1]
 [ 2]]


**EXERCISE:** How can the last line be rewritten to produce a row vector, instead of a column vector?

# CHALLENGE:
1. Write a function to compute the inverse of a 2x2 array. You may use the det function, but not inv. However, you are free to check your function using the inv function.